# Generated by Django 5.2 on 2025-04-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['timestamp'], name='core_locati_timesta_6c945d_idx'),
        ),
    ]
