# Generated by Django 5.2.12 on 2026-03-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_groups_remove_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='command',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='geofence',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='Command',
        ),
        migrations.DeleteModel(
            name='Geofence',
        ),
    ]
